### ISSUE TITLE
Maintanance?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/IRKGaussLegendre.jl#3]
Hey,
  I love this project and hope that we can keep it alive, but it's missing a ton of maintenance stuff. For example:

- Continuous integration
- Github actions like CompatHelper
- Convergence tests and other unit tests
- Registration
- Separation of package and test dependencies

How do you want to get there? Would you be interested in transferring to the SciML org so we could have some of our contributors keep this up to date? Or do you have some other plans?

**Comment by mikelehu** [comment]
Chris,

First of all, thank you for your interest in our project.  We would be happy to make a contribution with the implementation of the IRKGL16 solver to  DifferentialEquations.jl,  so we are interested in transferring to SciML.org.  Tell us if we can help in this process.

For next 2020-2021 we are going to continue implementing new solvers in Julia that  we hope you would find them interesting too
Thanks

**Comment by ChrisRackauckas** [comment]
Hey,
  I'll need to get access to do the transfer.

**Comment by mikelehu** [comment]
Chris,
I have given you access to the repository.

**Comment by ChrisRackauckas** [comment]
I don't think I have high enough permissions to migrate.

**Comment by mikelehu** [comment]
I have tried to transfer the repository to you, but Github shows me a warning:
"ChrisRackauckas already has a repository in the mikelehu/IRKGaussLegendre.jl network"

**Comment by ChrisRackauckas** [comment]
Not to me, to SciML

**Comment by mikelehu** [comment]
I have tried to transfer to SciML: 
"You don’t have the permission to create public repositories on SciML"

Transfer the repository to SciML,  I  need permission to create repositories.

**Comment by ChrisRackauckas** [comment]
I deleted my fork so you should be able to send it to me now.

**Comment by mikelehu** [comment]
I have already transferred it to you

**Comment by ChrisRackauckas** [comment]
And now it's in SciML. @kanav99 @YingboMa let's get this repo all setup to tag.

**Comment by ChrisRackauckas** [comment]
I did part of the packaging, but the major thing that is left is refactoring the Project.toml and the testing portions out of what would generally be the package. This is what CompatHelper is complaining about. Hopefully one of us will get to it this weekend, and by next week I hope we can do a release.

**Comment by mikelehu** [comment]
Thanks for your work

**Comment by ChrisRackauckas** [comment]
The repo has been packaged up, standard convergence tests capture the main behavior, CI and all is enabled, and this looks ready to go. I'm going to register it. Thanks for all of your work: this all looks great.
